"""empty message

Revision ID: 079764a2c4fa
Revises: 76bf44359b32
Create Date: 2020-07-16 02:05:38.212213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '079764a2c4fa'
down_revision = '76bf44359b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('Users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('Users', 'rating')
    op.drop_column('Users', 'total_rating')
    op.drop_column('Users', 'tagline')
    op.drop_column('Users', 'province')
    op.drop_column('Users', 'field_of_work')
    op.drop_column('Users', 'status')
    op.drop_column('Users', 'num_bids')
    op.drop_column('Users', 'introduction')
    op.drop_column('Users', 'num_of_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('num_of_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('introduction', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('num_bids', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('status', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('field_of_work', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('province', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('tagline', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('total_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('Users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
