"""empty message

Revision ID: 192733a9ec98
Revises: 
Create Date: 2020-06-02 06:27:10.459275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192733a9ec98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('status', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'status')
    # ### end Alembic commands ###
