"""empty message

Revision ID: 1c14653e8c2a
Revises: 5099b834781f
Create Date: 2020-06-27 02:00:26.236816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c14653e8c2a'
down_revision = '5099b834781f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('rating', sa.Float(), nullable=True))
    op.drop_column('Users', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('rate', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('Users', 'rating')
    # ### end Alembic commands ###
