"""empty message

Revision ID: 1d8bf7a1f04c
Revises: 
Create Date: 2021-03-08 17:49:16.989530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8bf7a1f04c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('task_url', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'task_url')
    # ### end Alembic commands ###
