"""empty message

Revision ID: 20363ae7a2bf
Revises: 192733a9ec98
Create Date: 2020-06-08 01:36:15.866199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20363ae7a2bf'
down_revision = '192733a9ec98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Tasks', 'Users', ['winner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tasks', type_='foreignkey')
    op.drop_column('Tasks', 'winner_id')
    # ### end Alembic commands ###
