"""empty message

Revision ID: 325e9df43a03
Revises: abb05311ee23
Create Date: 2020-07-09 18:51:14.672703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325e9df43a03'
down_revision = 'abb05311ee23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Company', sa.Column('member_sin', sa.DateTime(), nullable=True))
    op.alter_column('Company', 'company_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('Users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('Company', 'company_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('Company', 'member_sin')
    # ### end Alembic commands ###
