"""empty message

Revision ID: 5099b834781f
Revises: cdf643e503b8
Create Date: 2020-06-27 01:55:24.820675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5099b834781f'
down_revision = 'cdf643e503b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('rate', sa.String(length=10), nullable=True))
    op.drop_column('Users', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'rate')
    # ### end Alembic commands ###
