"""empty message

Revision ID: 52c0b01c04b4
Revises: 079764a2c4fa
Create Date: 2020-07-16 02:15:22.975530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c0b01c04b4'
down_revision = '079764a2c4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'status')
    # ### end Alembic commands ###
