"""empty message

Revision ID: 5485796e6696
Revises: 20363ae7a2bf
Create Date: 2020-06-09 08:23:08.658612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5485796e6696'
down_revision = '20363ae7a2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reviews', sa.Column('employer', sa.Integer(), nullable=True))
    op.add_column('Reviews', sa.Column('professional', sa.Integer(), nullable=True))
    op.drop_constraint('Reviews_prefessional_fkey', 'Reviews', type_='foreignkey')
    op.create_foreign_key(None, 'Reviews', 'Users', ['professional'], ['id'])
    op.create_foreign_key(None, 'Reviews', 'Users', ['employer'], ['id'])
    op.drop_column('Reviews', 'prefessional')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reviews', sa.Column('prefessional', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Reviews', type_='foreignkey')
    op.drop_constraint(None, 'Reviews', type_='foreignkey')
    op.create_foreign_key('Reviews_prefessional_fkey', 'Reviews', 'Users', ['prefessional'], ['id'])
    op.drop_column('Reviews', 'professional')
    op.drop_column('Reviews', 'employer')
    # ### end Alembic commands ###
