"""empty message

Revision ID: 70b928db70e1
Revises: 1c14653e8c2a
Create Date: 2020-06-27 02:14:26.603885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b928db70e1'
down_revision = '1c14653e8c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('total_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'total_rating')
    # ### end Alembic commands ###
