"""empty message

Revision ID: 76bf44359b32
Revises: e7fb480203be
Create Date: 2020-07-11 20:35:12.233390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76bf44359b32'
down_revision = 'e7fb480203be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Company')
    op.drop_constraint('Jobs_company_id_fkey', 'Jobs', type_='foreignkey')
    op.create_foreign_key(None, 'Jobs', 'Users', ['company_id'], ['id'])
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('Users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'Jobs', type_='foreignkey')
    op.create_foreign_key('Jobs_company_id_fkey', 'Jobs', 'Company', ['company_id'], ['id'])
    op.create_table('Company',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Company_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('worker_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('founded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('member_since', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Company_pkey'),
    sa.UniqueConstraint('email', name='Company_email_key')
    )
    # ### end Alembic commands ###
