"""empty message

Revision ID: 8b6ac5e77bed
Revises: 5485796e6696
Create Date: 2020-06-17 12:21:47.918385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6ac5e77bed'
down_revision = '5485796e6696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Offers', sa.Column('subject', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Offers', 'subject')
    # ### end Alembic commands ###
