"""empty message

Revision ID: 96ba118d8128
Revises: 3e80c0c8b9e5
Create Date: 2020-06-17 12:52:47.818271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ba118d8128'
down_revision = '3e80c0c8b9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Offers', sa.Column('offered_user', sa.Integer(), nullable=True))
    op.add_column('Offers', sa.Column('offers_user', sa.Integer(), nullable=True))
    op.alter_column('Offers', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('Offers_user_id_fkey', 'Offers', type_='foreignkey')
    op.create_foreign_key(None, 'Offers', 'Users', ['offered_user'], ['id'])
    op.create_foreign_key(None, 'Offers', 'Users', ['offers_user'], ['id'])
    op.drop_column('Offers', 'name')
    op.drop_column('Offers', 'user_id')
    op.drop_column('Offers', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Offers', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('Offers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Offers', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Offers', type_='foreignkey')
    op.drop_constraint(None, 'Offers', type_='foreignkey')
    op.create_foreign_key('Offers_user_id_fkey', 'Offers', 'Users', ['user_id'], ['id'])
    op.alter_column('Offers', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('Offers', 'offers_user')
    op.drop_column('Offers', 'offered_user')
    # ### end Alembic commands ###
