"""empty message

Revision ID: cdf643e503b8
Revises: 96ba118d8128
Create Date: 2020-06-17 13:11:18.630721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf643e503b8'
down_revision = '96ba118d8128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Offers', 'message',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('Offers', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Reviews', 'body',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Reviews', 'body',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('Offers', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Offers', 'message',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
