"""empty message

Revision ID: ce7c1ebe9ee9
Revises: 1d8bf7a1f04c
Create Date: 2021-03-13 15:19:26.560394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7c1ebe9ee9'
down_revision = '1d8bf7a1f04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Jobs', 'job_url')
    op.drop_column('Tasks', 'task_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('task_url', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('Jobs', sa.Column('job_url', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
