"""empty message

Revision ID: e2c56b982a20
Revises: 70b928db70e1
Create Date: 2020-07-08 17:53:16.408257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c56b982a20'
down_revision = '70b928db70e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jobs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('Jobs_user_id_fkey', 'Jobs', type_='foreignkey')
    op.create_foreign_key(None, 'Jobs', 'Company', ['company_id'], ['id'])
    op.drop_column('Jobs', 'user_id')
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('Users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'surname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('Jobs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Jobs', type_='foreignkey')
    op.create_foreign_key('Jobs_user_id_fkey', 'Jobs', 'Users', ['user_id'], ['id'])
    op.drop_column('Jobs', 'company_id')
    # ### end Alembic commands ###
