"""empty message

Revision ID: f738e41aa85f
Revises: 
Create Date: 2021-01-24 21:37:30.321098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f738e41aa85f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edu_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('exp_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exp_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('military', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('position_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Jobs', schema=None) as batch_op:
        batch_op.drop_column('position_level')
        batch_op.drop_column('military')
        batch_op.drop_column('exp_min')
        batch_op.drop_column('exp_max')
        batch_op.drop_column('edu_level')

    # ### end Alembic commands ###
